name: Deploy Keycloak to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 配置 AWS 凭证
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      # 3. 登录 ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-2 \
          | docker login --username AWS --password-stdin 533267398655.dkr.ecr.ap-southeast-2.amazonaws.com

      # 4. 构建 base 镜像
      - name: Build base image
        run: docker build -t identity-centre-base:latest -f Dockerfile_base .

      # 5. 构建 keycloak 镜像
      - name: Build keycloak image
        run: docker build -t keycloak:latest -f Dockerfile .

      # 6. 设置时间戳
      - name: Set build timestamp
        id: vars
        run: echo "TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      # 7. 推送到 ECR
      - name: Push Docker image to ECR
        run: |
          docker tag keycloak:latest 533267398655.dkr.ecr.ap-southeast-2.amazonaws.com/appzgatenz/topsale/identity-centre:latest
          docker tag keycloak:latest 533267398655.dkr.ecr.ap-southeast-2.amazonaws.com/appzgatenz/topsale/identity-centre:${TAG}
          docker push 533267398655.dkr.ecr.ap-southeast-2.amazonaws.com/appzgatenz/topsale/identity-centre:latest
          docker push 533267398655.dkr.ecr.ap-southeast-2.amazonaws.com/appzgatenz/topsale/identity-centre:${TAG}

      # 8. 触发 ECS Service 更新
      - name: Update ECS service
        run: |
          set -euo pipefail
          aws ecs update-service \
            --region ap-southeast-2 \
            --cluster IDENTITY-CENTRE-NONPROD \
            --service IDENTITY-CENTRE-NONPROD-SERVICE \
            --force-new-deployment

          # 调试：查看最近事件
          aws ecs describe-services \
            --region ap-southeast-2 \
            --cluster IDENTITY-CENTRE-NONPROD \
            --services IDENTITY-CENTRE-NONPROD-SERVICE \
            --query 'services[0].events[0:10]'

            